name: TABOX_DEPLOY

on:
  push:
    branches:
      - master

env:
  GIT_USER: fzf404
  GIT_EMAIL: nmdfzf404@163.com
  REPO_URL: git@github.com:fzf404/TaboxPage.git
  REPO_NAME: TaboxPage


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup
        run: |
          npm i

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build